// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5ApfhgCnaMzPyrQwzZfuwl_9ZG9gRxsA',
    appId: '1:479435303267:web:79567f1aeb4c7503214b56',
    messagingSenderId: '479435303267',
    projectId: 'todo-app-xp',
    authDomain: 'todo-app-xp.firebaseapp.com',
    storageBucket: 'todo-app-xp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9eISDARJ7lo3XjmuJv-FjyY8hQF2toQw',
    appId: '1:479435303267:android:00e66baef0598cd1214b56',
    messagingSenderId: '479435303267',
    projectId: 'todo-app-xp',
    storageBucket: 'todo-app-xp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIx1UQQL03HrgbU0_MQiC_7tvsXIgXgxo',
    appId: '1:479435303267:ios:ddb728ad170fdaa6214b56',
    messagingSenderId: '479435303267',
    projectId: 'todo-app-xp',
    storageBucket: 'todo-app-xp.appspot.com',
    iosClientId: '479435303267-at2gihn8tb47gb9ut3di9l44crpisgke.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppXp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIx1UQQL03HrgbU0_MQiC_7tvsXIgXgxo',
    appId: '1:479435303267:ios:55104e17c84ba42f214b56',
    messagingSenderId: '479435303267',
    projectId: 'todo-app-xp',
    storageBucket: 'todo-app-xp.appspot.com',
    iosClientId: '479435303267-1k8hp8b47vmi9hs72ksv9jupn3t6odda.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppXp.RunnerTests',
  );
}
